name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run DVC pipeline
      run: |
        pip install dvc
        dvc repro

    - name: Build Docker image
      run: |
        docker build -t stock-predictor-api .

    # Optional: Push to DockerHub or GHCR (you'll need Docker login + secrets)
